"""
Simple Credential Manager - Just stores cookies for gallery-dl
No validation, no testing - gallery-dl handles everything
"""
import keyring
import json
from typing import Optional, Dict
from datetime import datetime
from pathlib import Path
from core.logger import logger


class CredentialManager:
    """Manages authentication credentials - stores and retrieves only"""

    SERVICE_NAME = "GalleryDL-GUI"

    PLATFORMS = {
        "pixiv": "Pixiv",
        "fanbox": "Pixiv Fanbox",
        "patreon": "Patreon",
        "fantia": "Fantia",
        "subscribestar": "SubscribeStar"
    }

    # Required cookie names (for UI hints only)
    REQUIRED_COOKIES = {
        "fanbox": ["FANBOXSESSID"],
        "pixiv": ["PHPSESSID"],
        "patreon": ["session_id"],
        "fantia": ["_session_id"],
        "subscribestar": ["_subscribestar_session"]
    }

    def __init__(self):
        """Initialize credential manager"""
        self.keyring_available = self._check_keyring()

    def _check_keyring(self) -> bool:
        """Check if keyring is available"""
        try:
            keyring.get_keyring()
            return True
        except Exception as e:
            logger.warning(f"Keyring not available: {e}")
            return False

    def store_cookies(self, platform: str, cookie_string: str) -> bool:
        """
        Store cookies for a platform (no validation - gallery-dl will validate)

        Args:
            platform: Platform identifier
            cookie_string: Cookie string in any format

        Returns:
            True if stored successfully
        """
        if not self.keyring_available:
            return False

        try:
            # Auto-format: Add cookie name if user just pasted the value
            cookie_string = cookie_string.strip()
            if '=' not in cookie_string and platform in self.REQUIRED_COOKIES:
                required_names = self.REQUIRED_COOKIES[platform]
                if required_names:
                    cookie_name = required_names[0]
                    cookie_string = f"{cookie_name}={cookie_string}"

            # Store credentials
            credentials = {
                "auth_method": "cookies",
                "cookies": cookie_string,
                "stored_at": datetime.now().isoformat()
            }

            keyring.set_password(
                self.SERVICE_NAME,
                f"{platform}_credentials",
                json.dumps(credentials)
            )
            return True

        except Exception as e:
            logger.error(f"Error storing cookies: {e}")
            return False

    def get_cookies(self, platform: str) -> Optional[str]:
        """Get cookie string for a platform"""
        if not self.keyring_available:
            return None

        try:
            credentials_json = keyring.get_password(
                self.SERVICE_NAME,
                f"{platform}_credentials"
            )

            if credentials_json:
                credentials = json.loads(credentials_json)
                return credentials.get("cookies")

            return None

        except Exception as e:
            logger.error(f"Error retrieving cookies: {e}")
            return None

    def get_credentials(self, platform: str) -> Optional[Dict]:
        """Get full credentials dict for a platform (for username/password auth)"""
        if not self.keyring_available:
            return None

        try:
            credentials_json = keyring.get_password(
                self.SERVICE_NAME,
                f"{platform}_credentials"
            )

            if credentials_json:
                return json.loads(credentials_json)

            return None

        except Exception:
            return None

    def write_cookie_file(self, platform: str, output_path: Path) -> bool:
        """
        Write cookies to Netscape format file for gallery-dl

        Args:
            platform: Platform identifier
            output_path: Path to write cookie file

        Returns:
            True if successful
        """
        cookie_string = self.get_cookies(platform)
        if not cookie_string:
            return False

        try:
            # Write in Netscape format
            with open(output_path, 'w') as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# Generated by FanFan Gallery-DL\n\n")

                # Parse and write cookies
                for cookie in cookie_string.split("; "):
                    if "=" in cookie:
                        name, value = cookie.split("=", 1)
                        # Simple format - gallery-dl will handle the details
                        f.write(f".example.com\tTRUE\t/\tFALSE\t0\t{name}\t{value}\n")

            return True

        except Exception as e:
            logger.error(f"Error writing cookie file: {e}")
            return False

    def delete_cookies(self, platform: str) -> bool:
        """Delete stored cookies for a platform"""
        if not self.keyring_available:
            return False

        try:
            keyring.delete_password(self.SERVICE_NAME, f"{platform}_credentials")
            return True
        except Exception as e:
            logger.error(f"Error deleting cookies: {e}")
            return False

    def has_cookies(self, platform: str) -> bool:
        """Check if platform has stored cookies"""
        return self.get_cookies(platform) is not None

    def store_browser_cookies(self, browser: str, platform: str) -> bool:
        """
        Import cookies from a browser's cookie database.

        Args:
            browser: Browser name (chrome, firefox, edge, comet)
            platform: Platform identifier

        Returns:
            True if stored successfully
        """
        # gallery-dl supports --cookies-from-browser directly,
        # so we store the browser name as the auth method
        if not self.keyring_available:
            return False

        try:
            credentials = {
                "auth_method": "browser",
                "browser": browser.lower(),
                "stored_at": datetime.now().isoformat()
            }

            keyring.set_password(
                self.SERVICE_NAME,
                f"{platform}_credentials",
                json.dumps(credentials)
            )
            return True

        except Exception as e:
            logger.error(f"Error storing browser cookies: {e}")
            return False

    def store_cookie_file(self, platform: str, file_path: Path) -> tuple:
        """
        Import cookies from a Netscape or JSON cookie file.

        Args:
            platform: Platform identifier
            file_path: Path to cookie file

        Returns:
            Tuple of (success: bool, message: str)
        """
        if not self.keyring_available:
            return False, "Keyring not available"

        try:
            if not file_path.exists():
                return False, f"File not found: {file_path}"

            content = file_path.read_text(encoding='utf-8').strip()

            if not content:
                return False, "Cookie file is empty"

            # Try to detect format and extract cookies
            cookie_string = ""

            if file_path.suffix == '.json':
                # JSON format - array of cookie objects
                try:
                    cookies = json.loads(content)
                    if isinstance(cookies, list):
                        parts = []
                        for cookie in cookies:
                            name = cookie.get('name', '')
                            value = cookie.get('value', '')
                            if name and value:
                                parts.append(f"{name}={value}")
                        cookie_string = "; ".join(parts)
                    else:
                        return False, "JSON file must contain an array of cookie objects"
                except json.JSONDecodeError:
                    return False, "Invalid JSON format"
            else:
                # Netscape format - tab-separated lines
                parts = []
                for line in content.split('\n'):
                    line = line.strip()
                    if not line or line.startswith('#'):
                        continue
                    fields = line.split('\t')
                    if len(fields) >= 7:
                        name = fields[5]
                        value = fields[6]
                        if name and value:
                            parts.append(f"{name}={value}")
                cookie_string = "; ".join(parts)

            if not cookie_string:
                return False, "No valid cookies found in file"

            # Store using the standard method
            success = self.store_cookies(platform, cookie_string)
            if success:
                return True, f"Imported cookies successfully"
            else:
                return False, "Failed to store cookies"

        except Exception as e:
            return False, f"Error reading cookie file: {e}"

    def store_username_password(self, platform: str, username: str, password: str) -> bool:
        """
        Store username/password credentials for a platform.

        Args:
            platform: Platform identifier
            username: Username or email
            password: Password

        Returns:
            True if stored successfully
        """
        if not self.keyring_available:
            return False

        try:
            credentials = {
                "auth_method": "username",
                "username": username,
                "password": password,
                "stored_at": datetime.now().isoformat()
            }

            keyring.set_password(
                self.SERVICE_NAME,
                f"{platform}_credentials",
                json.dumps(credentials)
            )
            return True

        except Exception as e:
            logger.error(f"Error storing credentials: {e}")
            return False

    def get_auth_method(self, platform: str) -> Optional[str]:
        """Get the authentication method for a platform"""
        if not self.keyring_available:
            return None

        try:
            credentials_json = keyring.get_password(
                self.SERVICE_NAME,
                f"{platform}_credentials"
            )

            if credentials_json:
                credentials = json.loads(credentials_json)
                return credentials.get("auth_method")

            return None

        except Exception:
            return None

    def get_browser(self, platform: str) -> Optional[str]:
        """Get browser name for browser-based auth"""
        if not self.keyring_available:
            return None

        try:
            credentials_json = keyring.get_password(
                self.SERVICE_NAME,
                f"{platform}_credentials"
            )

            if credentials_json:
                credentials = json.loads(credentials_json)
                if credentials.get("auth_method") == "browser":
                    return credentials.get("browser")

            return None

        except Exception:
            return None

    def get_hint(self, platform: str) -> str:
        """Get helpful hint for what cookies are needed"""
        if platform in self.REQUIRED_COOKIES:
            required = self.REQUIRED_COOKIES[platform]
            return f"Required cookies: {', '.join(required)}"
        return "Paste your cookies from Cookie-Editor or browser"
